### ISSUE TITLE
About downstream datasets

### ISSUE THREAD

**Issue by flyz1** [THUDM/GCC#18]
Hello, I want to run code on the Cora and Citeseer dataset, but I found no downstream dataset named it.
So, could you please provide the code for generating downstream datasets? or would you mind offering me the Cora and Citeseer files you have generated?
Thanks a million!

**Comment by qibinc** [comment]
Hi @flyz1 ,

Thanks for your interest. This work is not intended to run on datasets like Cora and Citeseer directly because of their attributes (Please see discussions in the paper on this 2.1 Vertex Similarity and 3.3 GCC Design Q1). Combining GCC and a conventional GCN would be interesting but is beyond the scope of this work.

Best,

**Comment by flyz1** [comment]
OK, thanks for your answer very much!
