### ISSUE TITLE
Redundant edges in NodeClassificationDataset

### ISSUE THREAD

**Issue by JiangTanZJU** [THUDM/GCC#4]
At https://github.com/THUDM/GCC/blob/master/gcc/datasets/data_util.py#L86, we can see bidirectional edges have been added to the list.
![image](https://user-images.githubusercontent.com/39088437/87409507-996ef080-c5f7-11ea-9c9d-d2e89a252dd9.png)
However, in the process of building graph, https://github.com/THUDM/GCC/blob/master/gcc/datasets/graph_dataset.py#L307, both the edges from src to dst and from dst to src were added to the graph. I think just edges from src to dst are enough. Why do we need double add_edges operations here?
![image](https://user-images.githubusercontent.com/39088437/87409536-a5f34900-c5f7-11ea-9544-86bb3573314c.png)

**Comment by qibinc** [comment]
Hi @JiangTanZJU ,

Thanks for pointing out this. As you said, the double add_edges operations **are not needed** for those node classification datasets (Edgelist class). Initially we use this to ensure both node classification datasets and graph classification datasets (which are imported from DGL) are undirected. I double-checked after you proposed this issue and it turned out that these redundant operations do affect the results. Specifically, the accuracies on most datasets will be promoted a little bit after removing them properly. We will fix this in a later commit. Thanks for your contribution!

Best,
